webtalk_init -webtalk_dir /opt/Xilinx/SDK/2018.2/0projects/customip/customip.sim/sim_1/behav/xsim/xsim.dir/mb_system_wrapper_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Thu Nov 29 16:46:58 2018" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2258646" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "b47d2302-147c-48fc-9436-43ede2c225f5" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "fa4db607bc3b47df91545d826f54aa4e" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "78" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 16.04.5 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD FX(tm)-6300 Six-Core Processor" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1405.601 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "2" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "255945 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "11" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "20.31_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "143244_KB" -context "xsim\\usage"
webtalk_transmit -clientid 867704651 -regid "" -xml /opt/Xilinx/SDK/2018.2/0projects/customip/customip.sim/sim_1/behav/xsim/xsim.dir/mb_system_wrapper_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html /opt/Xilinx/SDK/2018.2/0projects/customip/customip.sim/sim_1/behav/xsim/xsim.dir/mb_system_wrapper_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm /opt/Xilinx/SDK/2018.2/0projects/customip/customip.sim/sim_1/behav/xsim/xsim.dir/mb_system_wrapper_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
