# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /opt/Xilinx/Vivado/2018.2/customip/customip.srcs/sources_1/bd/mb_system/ip/mb_system_xbar_0/mb_system_xbar_0.xci
# IP: The module: 'mb_system_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /opt/Xilinx/Vivado/2018.2/customip/customip.srcs/sources_1/bd/mb_system/ip/mb_system_xbar_0/mb_system_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb_system_xbar_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /opt/Xilinx/Vivado/2018.2/customip/customip.srcs/sources_1/bd/mb_system/ip/mb_system_xbar_0/mb_system_xbar_0.xci
# IP: The module: 'mb_system_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /opt/Xilinx/Vivado/2018.2/customip/customip.srcs/sources_1/bd/mb_system/ip/mb_system_xbar_0/mb_system_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb_system_xbar_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
