# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /opt/Xilinx/Vivado/2018.2/customip/customip.srcs/sources_1/bd/mb_system/ip/mb_system_clk_wiz_1_4/mb_system_clk_wiz_1_4.xci
# IP: The module: 'mb_system_clk_wiz_1_4' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /opt/Xilinx/Vivado/2018.2/customip/customip.srcs/sources_1/bd/mb_system/ip/mb_system_clk_wiz_1_4/mb_system_clk_wiz_1_4_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb_system_clk_wiz_1_4'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /opt/Xilinx/Vivado/2018.2/customip/customip.srcs/sources_1/bd/mb_system/ip/mb_system_clk_wiz_1_4/mb_system_clk_wiz_1_4.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb_system_clk_wiz_1_4'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /opt/Xilinx/Vivado/2018.2/customip/customip.srcs/sources_1/bd/mb_system/ip/mb_system_clk_wiz_1_4/mb_system_clk_wiz_1_4_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb_system_clk_wiz_1_4'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /opt/Xilinx/Vivado/2018.2/customip/customip.srcs/sources_1/bd/mb_system/ip/mb_system_clk_wiz_1_4/mb_system_clk_wiz_1_4.xci
# IP: The module: 'mb_system_clk_wiz_1_4' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /opt/Xilinx/Vivado/2018.2/customip/customip.srcs/sources_1/bd/mb_system/ip/mb_system_clk_wiz_1_4/mb_system_clk_wiz_1_4_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb_system_clk_wiz_1_4'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /opt/Xilinx/Vivado/2018.2/customip/customip.srcs/sources_1/bd/mb_system/ip/mb_system_clk_wiz_1_4/mb_system_clk_wiz_1_4.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb_system_clk_wiz_1_4'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /opt/Xilinx/Vivado/2018.2/customip/customip.srcs/sources_1/bd/mb_system/ip/mb_system_clk_wiz_1_4/mb_system_clk_wiz_1_4_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mb_system_clk_wiz_1_4'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
